source/includes/_rate_limits.md

rate limits doc updated

---

source/includes/_websocket_api.md

fix: fill resp

---

source/includes/_websocket_api.md

ohlc candlestick added

---

source/includes/_websocket_api.md

formatting for ohlc

---

source/includes/_websocket_api.md

fixing order update limit price

---

source/includes/_websocket_api.md

adding position snapshot info

---

source/includes/_websocket_api.md

alignment fix

---

source/includes/_rest_api.md
swagger_v2.json

deadman documentation

---

source/includes/_websocket_api.md

add documentation for spot 30m twap

---

source/includes/_authentication.md

api key changes

---

source/includes/_rest_api.md

improves bracker order doc

---

source/includes/_rest_api.md

size limit batch

---

source/includes/_rest_api.md

adds batch order mod

---

source/includes/_rest_api.md

cancel all orders mod

---

source/includes/_rest_api.md
swagger_v2.json

add more comments to swagger and update readme to reflect mmp changes

---

source/includes/_websocket_api.md
swagger_v2.json

socket enhancements

---

source/includes/_websocket_api.md

socket symbol: all clarity

---

source/includes/_websocket_api.md

socket api fix

---

source/includes/_websocket_api.md

socket changes

---

source/includes/_websocket_api.md
swagger_v2.json

Socket api changes

---

source/includes/_websocket_api.md

l2_updates docs added

---

swagger_v2.json

adds sub wallet transfer

---

source/includes/_rest_api.md
swagger_v2.json

adds subaccount related apis

---

source/includes/_rest_api.md
swagger_v2.json

adds batch order fixes

---

source/includes/_websocket_api.md

Added l2update error message doc

---

source/includes/_websocket_api.md

Publish intervals for l1ob, l2ob, l2u added

---

source/includes/_websocket_api.md

l2_updates add subscribe and max symbols fix

---

source/includes/_websocket_api.md

l2_updates subscribe message fix

---

source/includes/_rest_api.md
swagger_v2.json

Edit and batch edit have post_only flag

---

source/includes/_websocket_api.md

fixes funding rate

---

source/includes/_authentication.md

APIkey whitelisting docs added

---

source/includes/_authentication.md

IP whitelist small fix

---

source/includes/_rest_api.md
swagger_v2.json

fixes wallet transfer

---

source/includes/_rest_api.md
source/includes/_websocket_api.md
swagger_v2.json

L2orderbook, l2updates json docs. TRAD 1204

---

source/includes/_rest_api.md
source/includes/_websocket_api.md
swagger_v2.json

Get order by client oid. Typo fixes

---

source/includes/_rest_api.md
swagger_v2.json

GET positions added underlying_asset_symbol param

---

source/includes/_websocket_api.md

l1ob, l1ob_c changes

---

swagger_v2.json

Dilip|Updating doc for Create and Batch OrderRequest

---

.circleci/config.yml

Deploy circle ci

---

source/includes/_rest_api.md
swagger_v2.json

tets tcicd

---

source/includes/_changelog.md
source/includes/_rate_limits.md
source/includes/_rest_api.md
source/includes/_rest_api_v1.md
source/includes/_websocket_api.md
swagger_v2.json
widdershins_templates/openapi3/main.dot

Rate limits docs updated

---

swagger_v2.json

batch order payloads corrected

---

source/includes/_websocket_api.md

Commented out l1ob and l1ob_c

---

source/includes/_rest_api.md

Better format and docs

---

swagger_v2.json
widdershins_templates/openapi3/main.dot

added option of update trading preferences

---

source/includes/_rate_limits.md
source/includes/_types.md

rate limit section updated for api and products

---

source/includes/_general_information.md
source/includes/_websocket_api.md
swagger_v2.json

sample code for websocket added

---

source/includes/_changelog.md
source/includes/_rest_api.md
source/includes/_websocket_api.md
swagger_v2.json

Socket: Candlestick, announcement. Rest: positions

---

source/includes/_authentication.md
swagger_v2.json

improved common error codes

---

source/includes/_websocket_api.md

Added rate limits for websocket

---

source/includes/_authentication.md
source/includes/_errors.md

> Justification
- We plan to add 403 http status listed and possible reasons behind it for the api users.
- Few programming language http client do not add user-agent by default and those requests are rejected by Cloudflare(cdn) itself. Similarly, few hosted environments hide their IP in the requests and they aer also rejected by cdn before entering into Delta api gateway.
> Implementation
-  Added documentation for error code 403 status and troubleshooting steps.
> Screenshots

Added error code 403 description and troubleshooting steps
